# 设置缩进宽度为 4 个空格
tab_spaces = 4

# 行长, 后面多个 width 都不能超过这个参数的值
max_width = 160

# 在函数调用的参数列表中换行
fn_call_width = 160

# 在链式方法调用中换行
chain_width = 160

# 数组长度
array_width = 160

# 大括号换行方式
brace_style = "SameLineWhere"

# 在 if/else 表达式中换行
control_brace_style = "AlwaysSameLine"

# 强制 where 占 行
where_single_line = true

# 垂直排列行末添加逗号
trailing_comma = "Vertical"

# 在运算符左右添加空格
space_before_colon = false
space_after_colon = true

# 禁用自动换行
hard_tabs = false
wrap_comments = false

# 格式化注释里的代码
format_code_in_doc_comments = true